name: push-build-release
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.event.pull_request.base.ref }} 
on:

  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main,develop]
jobs:
  build_test_package:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    uses: EddyTheCo/Common/.github/workflows/build-test-install.yml@v0.5.2
    with:
      os: ${{ matrix.os }}
      qtModules: 'qtwebsockets qtshadertools'
      qtVersion: '6.8.1'
  build-android:
    strategy:
      matrix:
        qtArch: ['android_arm64_v8a','android_armv7']

    uses: EddyTheCo/Common/.github/workflows/build-android.yml@v0.5.2
    with:
      qtModules: 'qtwebsockets qtshadertools'
      qtTarget: 'client'
      qtVersion: '6.8.1'
      qtArch: ${{ matrix.qtArch }}
    secrets:
      QT_ANDROID_KEYSTORE_STORE_PASS:  ${{ secrets.QT_ANDROID_KEYSTORE_STORE_PASS }}
  build-wasm:
    uses: EddyTheCo/Common/.github/workflows/build-wasm.yml@v0.5.2
    with:
      qtModules: 'qtwebsockets qtshadertools'
      qtVersion: '6.6.0'
      emsdkVersion: '3.1.37'
      deploy_dev: ${{ (startsWith(github.base_ref, 'main'))&&(startsWith(github.head_ref, 'develop')) }}

  release-deploy:
    if: ${{ ((startsWith(github.base_ref, 'main'))&&(startsWith(github.head_ref, 'develop')))||(startsWith(github.ref, 'refs/tags/v')) }}
    needs: [build_test_package,build-android,build-wasm]
    uses: EddyTheCo/Common/.github/workflows/release.yml@v0.5.2
    with:
      is_app: true 
      release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      release_wasm: true 
    permissions:
      contents: write
      pages: write
      id-token: write

